# Generated by Django 5.1.3 on 2025-02-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=30)),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
